[package]
name = "dji-log-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
binrw = "0.13.1"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
crc64 = "2.0.0"
